base_url = "https://gokulprathin8.github.io/gokuls-blog"

taxonomies = [ { name = "tags" } ]

compile_sass = true

build_search_index = false
#generate_feed = true

title = "gokul rants about tech."
description = "all things about tech, architecture design, infra and ai"

[markdown]
highlight_code = true
theme = "simple-dev-blog"

[extra]

dark_mode = true

nav = [
  { name = "About", path = "https://gokuls-portfolio.vercel.app/" }
]

latest_text = "Check out my latest post:"

icon = "icon.png"
profile_small = "icon.png"
profile_large = "icon.png"

accent = "#6BCB77"
accent_light = "#D4F2DD"

author = "John Doe"

footer_about = """
All things tech.
"""

footer_page = """
© 2025, all rights reserved
"""

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""
